// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVirPGB7OsiMdtCipEyG6AocIueuvrh2U',
    appId: '1:38399384797:web:acf62f54747b7cfd7e8f34',
    messagingSenderId: '38399384797',
    projectId: 'iiit-bhopal-e4df3',
    authDomain: 'iiit-bhopal-e4df3.firebaseapp.com',
    storageBucket: 'iiit-bhopal-e4df3.appspot.com',
    measurementId: 'G-45CLDN64ZJ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVirPGB7OsiMdtCipEyG6AocIueuvrh2U',
    appId: '1:38399384797:web:240e51032918d6277e8f34',
    messagingSenderId: '38399384797',
    projectId: 'iiit-bhopal-e4df3',
    authDomain: 'iiit-bhopal-e4df3.firebaseapp.com',
    storageBucket: 'iiit-bhopal-e4df3.appspot.com',
    measurementId: 'G-27JZFQBGVM',
  );

}